import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Masthead from '../components/masthead'
import AboutUs from '../components/aboutus'
import Skills from '../components/skills'
import Works from '../components/works'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vtificial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Masthead />
      <AboutUs/>
      <Skills/>
      <Works/>
    </div>
  )
}

export default Home
